### ISSUE TITLE
obtained tx not done

### ISSUE THREAD

**Issue by enkumber** [chris-belcher/joinmarket#203]
I noticed in terminal that I got the message: obtained tx
But no  transaction was made. Is this normal ?

**Comment by chris-belcher** [comment]
Which joinmarket script were you running? (options are sendpayment.py, yield-generator.py, tumbler.py etc)

It means the coinjoin tx deal didnt happen, probably because the other bot didn't respond for some reason. It might be normal if the other bot crashes or something.

If you were running sendpayment.py, close it and try again.
If you were running yield-generator.py, leave it, the taker didn't respond for some reason.
If you were running tumbler.py, whoops your tumbling has been stopped and will have to be started again from the start.

#166 should be a finished shortly which would go a long way to improving user experience when this happens.

**Comment by enkumber** [comment]
it was yeld-generator. I was just making sure it's nothing wrong on my side. Thank you
