### ISSUE TITLE
Implement querying blockchain with bitcoind json-rpc

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/joinmarket#22]
Needs https://github.com/chris-belcher/joinmarket/issues/13 and a few others done first.

Give users the option to query bitcoind with a local copy of the blockchain, as well as http query blockchain explorers.

Bitcoind needs to be run with -txindex=1 so you can look up an arbitrary txid.

**Comment by chris-belcher** [comment]
Notes on bitcoind RPC.

To lookup UTXOs on an address, you indeed need to importprivkey them and then listunspent.
This can take a long time, of course. However since we only need to do it once at the beginning before the bot connects to IRC, it not too much of a problem to have a long lookup sequence. I imagine the watch-only addresses feature of the new bitcoind is just a way of doing this without having to know the private key.

Using -txindex you can look up any txid and get a transaction back, using gettransaction or getrawtransaction. Very useful, for privacy too since the status quo involves leaking which addresses you're interested in to blockr.

Apparently getrawtransaction queries the mempool (unconfirmed tx) and the txindex.

You can use -blocknotify to be notified when a new block arrives, you get given the blockhash as an argument, which you can pass to getblock, that will give you a list of TXIDs which you can pass to gettransaction. In this way you can learn when a transaction has been confirmed.

A way to learn when a transaction is unconfirmed could be to importprivkey with rescan=false and then check with -walletnotify. According to this [bitcointalk post](https://bitcointalk.org/index.php?topic=203438.msg2130516#msg2130516) we could use walletnotify for both unconfirmed and confirmed.

The gettxout call might be useful for finding unconfirmed transactions too, there is an option includemempool=true. Worth investigating.

**Comment by AdamISZ** [comment]
Thanks for that.

Yes, watchonly means you don't need to import the privkey. Maybe that doesn't really matter.

As I was mentioning on IRC, we also need to check spent txos as well as utxos, at least at startup to check for used status. To do this I used the listtransactions RPC call applied to a separate 'watchonly' account, and then filtered the output by address. I don't think the indexes can help with that (?) - getting all transactions (not just utxos) on a per-address basis, if you don't have the txids?

>You can use -blocknotify to be notified when a new block arrives, you get given the blockhash as an argument, which you can pass to getblock, that will give you a list of TXIDs which you can pass to gettransaction. In this way you can learn when a transaction has been confirmed.

Ah, this is cool, will read up on it. You can easily get unconfirmed utxos with listunspent, but for mainnet (rather than regtest), this blocknotify feature could be very important.

**Comment by chris-belcher** [comment]
The watchonly thing will be useful so a copy of the private key isnt also floating around in someone's wallet.dat file ready to be stolen.

I think -walletnotify might end up being all we need. Since it notifies us for both unconfirmed and confirmed.

**Comment by chris-belcher** [comment]
Done with https://github.com/chris-belcher/joinmarket/commit/d4fa38759c5efdc772e5f9db1288294beb666643
