### ISSUE TITLE
Tumbler waits for confirm failed pushtx w/blockr.

### ISSUE THREAD

**Issue by tailsjoin** [chris-belcher/joinmarket#233]
Testing the tumbler today on TAILS using blockr. The first tx failed on the push, but the tumbler kept waiting for the confirm until I killed it.

https://paste.debian.net/plainh/90dacca1/

Edit: This on the crude-taker-recovery2 branch.

**Comment by tailsjoin** [comment]
Unencrypted: https://paste.debian.net/plainh/9ec7e741/

**Comment by chris-belcher** [comment]
Nothing seems obviously wrong with that transaction which failed to be broadcast.

Right now some of the UTXOs are already spent, that could just be because the owner spent it in another transaction. I put the spent ones into a blockchain explorer and found they were all spent around 2-3 hours ago, so they were not obviously invalid UTXOs.

Fundamentally this breaking of your tumbler happened because there's no timeout to the waiting-for-a-tx code https://github.com/chris-belcher/joinmarket/issues/118

**Comment by tailsjoin** [comment]
Closing then, as redundant.
