### ISSUE TITLE
Maker recoded to use MessageChannel fails at encryption

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/joinmarket#46]
In commit https://github.com/chris-belcher/joinmarket/commit/46c85479ce4034d12289e3df4a8441ffe837fce6

I've recoded the classes to use the MessageChannel base class. All I did was move the IRC specific code into irc.py and replace it with functions and callbacks in the Maker and Taker classes.
It was successful with Taker and OrderbookWatch, but for Maker and yield generator it appears to get the encryption wrong. The taker on the other side fails to decrypt the !ioauth command and crashes. Before that, the !auth command is correctly received by the maker and decrypted.

I have tested the old and new (which uses MessageChannel) takers on the old kind of makers and it works.
I've tried a few things but no longer know what to do to try to debug this.

**Comment by AdamISZ** [comment]
Problem occurs because of utxo_list being in unicode format at line 108: https://github.com/chris-belcher/joinmarket/commit/46c85479ce4034d12289e3df4a8441ffe837fce6#diff-fc8ffb45857c1b6539f3506c6c16a515R108

Easy fix is to call str(','.join(utxo_list). (Although, a more generic way of addressing this problem is probably worth looking at).

Also on line 121, there is a typo: sig_list not sigs_list.

I just tried an example, it went through except it seems push_tx didn't complete (got complete raw tx but didn't see on network; will look into it).

**Comment by AdamISZ** [comment]
>I just tried an example, it went through except it seems push_tx didn't complete (got complete raw tx but didn't see on network; will look into it).

Forget that, the push command had been commented out. The complete transaction went through fine.

**Comment by chris-belcher** [comment]
gaah!
I remember removing that str() for some silly reason. You can see it's still here. https://github.com/chris-belcher/joinmarket/blob/master/maker.py#L51

My bad. Well done for finding it.
