### ISSUE TITLE
ERROR not enough liquidity in the orderbook

### ISSUE THREAD

**Issue by dreboli** [chris-belcher/joinmarket#96]
After a couple of hours tumbling I get:

woken
coinjoining 55872
[2015/05/28 18:51:30] ERROR not enough liquidity in the orderbook n=2 suitable-counterparties=1
average fee = 0.0
waiting for liquidity
[2015/05/28 18:51:40] ERROR not enough liquidity in the orderbook n=2 suitable-counterparties=1
average fee = 0.0

What does this mean?
What can I do?
What happened with my coins?
Is this the right place to ask these kind of questions, or should I rather go the /r/joinmarket or somewhere else?

**Comment by chris-belcher** [comment]
It means the orderbook did not have the necessary orders to create of coinjoin of that size 55872 satoshi. So the bot entered a loop, waiting for a suitable order showed up.

It looks like 55872 satoshi is too small, it's below everyone's `minimum amount` in the orderbook. Try using this command line option which sets a floor on the random coinjoin amounts generated.

	  -s MINCJAMOUNT, --mincjamount=MINCJAMOUNT
	                minimum coinjoin amount in transaction

Your coins will still be in the wallet file, unless some have been sent to your destination addresses already. Run wallet-tool.py to see them, perhaps with a higher max mix depth (with the -m flag) since tumbler.py might go to higher depths than the default of 5. You can restart the tumbler from a higher mixing depth than zero if you just want to pick up where you left off.

Thanks for trying it out. It's helpful to me to see where users trip, I've already edited the wiki based on this.

Posting on /r/joinmarket might be slightly better because I suspect more people read that, the community would learn more by the questions being answered.

**Comment by dreboli** [comment]
Does the script has to be running and online for 5.32 hours while tumbling?

**Comment by chris-belcher** [comment]
Depends on your configuration. You can choose parameters like average waiting time and amount of transactions to do, which will affect how long it takes.

Most of the time the tumbler script is just waiting for confirmations.
